### ISSUE TITLE
improve IA for pages (RHS links)

### ISSUE THREAD

**Issue by kaushikgopal** [kaushikgopal/henry-hugo#7]
# Background

IA = Information Architecture

* In many of the important pages like blog list & single post page, there's wasted space on the sides. 
* While I prefer the minimal aesthetic (like a paper like reading experience) the wasted space is valuable unused real estate.
* Additionally, in important pages like the blog list index, its ridiculous to expect people to scroll all the way at the bottom to navigate to different parts of the site. just look at [kau.sh/blog](https://kau.sh/blog) where i have > 50 posts. 

# Solution

- add minimal/small permanent links to the RHS
- surface page specific content that could be more useful (e.g. categories on the post-list index page)
- i could potentially remove the entire jquery scroll to the top/bottom (or put it behind a settings) thing if the IA is done right

### Every page

- About me
- Subscribe (All)

### List page (/blog etc)

- cateogories

### Single Post page

- this category
- related (point to the bottom of the page)

# Todo

- [ ] add a rhs side bar (icon with text)
- [ ] add content specific links for single post
- [ ] add content specific links for blog list
- [ ] mobile pages show only icons

**Comment by kaushikgopal** [comment]
done! really happy with this one.
